[project]
name = "fabric-sqlmesh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "dlt[mssql]>=1.10.0",
    "dotenv>=0.9.9",
    "sqlmesh[mssql-odbc]",
]
